version 0.2
phases:
  install:
     commands:
        - yum update -y
        - yum install httpd -y
        - yum install git -y
  pre_build:
     commands:
        - systemctl start httpd
        - git clone https://github.com/priya2097/azure-app
  build:
     commands:
        - mv azure-app /var/www/html/
  artifacts:
     files: 
       - /var/www/html/index.html
    
    
